version: '3'
services:
  py:
    build: .
    environment:
      AC_USERNAME: ${AC_USERNAME}
      AC_PASSWORD: ${AC_PASSWORD}
    volumes:
      - .:/usr/src/app
      - ./bin/acc:/usr/local/bin/acc
    working_dir: /usr/src/app
    tty: true
    stdin_open: true
